import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../../../config/theme.dart';
import '../../../core/widgets/ds_widgets.dart';
import '../../../core/models/models.dart';
import '../../../core/providers/app_providers.dart';

class SafetyFileSubmissionView extends ConsumerStatefulWidget {
  final String contractorId;
  final String projectId;

  const SafetyFileSubmissionView({
    super.key,
    required this.contractorId,
    required this.projectId,
  });

  @override
  ConsumerState<SafetyFileSubmissionView> createState() => _SafetyFileSubmissionViewState();
}

class _SafetyFileSubmissionViewState extends ConsumerState<SafetyFileSubmissionView> {
  final _functions = FirebaseFunctions.instanceFor(region: 'europe-west1');
  bool _isGeneratingPdf = false;

  Future<void> _updateFindingStatus(Finding finding, FindingStatus newStatus, String comment) async {
    final user = ref.read(userProfileProvider).valueOrNull;
    if (user == null) return;

    final db = ref.read(firestoreProvider);
    final historyEntry = {
      'status': newStatus.name,
      'timestamp': DateTime.now().toIso8601String(),
      'comment': comment,
      'userId': user.uid,
    };

    await db.collection('findings').doc(finding.findingId).update({
      'status': newStatus.name,
      'modifiedBy': user.uid,
      'modifiedAt': FieldValue.serverTimestamp(),
      'statusHistory': FieldValue.arrayUnion([historyEntry]),
    });
  }

  void _showUpdateDialog(Finding finding) {
    final commentCtrl = TextEditingController();
    FindingStatus? selectedStatus;

    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        title: const Text('Update Finding Status'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            DropdownButtonFormField<FindingStatus>(
              decoration: const InputDecoration(labelText: 'New Status'),
              items: FindingStatus.values.map((s) {
                return DropdownMenuItem(value: s, child: Text(s.name.toUpperCase()));
              }).toList(),
              onChanged: (v) => selectedStatus = v,
            ),
            GSpacing.vMd,
            TextFormField(
              controller: commentCtrl,
              decoration: const InputDecoration(labelText: 'Comment / Reason'),
              maxLines: 2,
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel')),
          FilledButton(
            onPressed: () {
              if (selectedStatus != null && commentCtrl.text.isNotEmpty) {
                _updateFindingStatus(finding, selectedStatus!, commentCtrl.text);
                Navigator.pop(ctx);
              }
            },
            child: const Text('Update'),
          ),
        ],
      ),
    );
  }

  Future<void> _generateReport(String submissionId) async {
    setState(() => _isGeneratingPdf = true);
    try {
      final res = await _functions.httpsCallable('generateSafetyFileReport').call({
        'submissionId': submissionId,
      });

      final data = res.data as Map;
      final findingsData = data['findings'] as List;

      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          build: (context) => [
            pw.Header(level: 0, child: pw.Text('Safety File Audit Report')),
            pw.Text('Submission ID: $submissionId'),
            pw.Text('Generated At: ${data['generatedAt']}'),
            pw.Text('Generated By: ${data['generatedBy']}'),
            pw.SizedBox(height: 20),
            pw.Text('Findings:', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 18)),
            pw.SizedBox(height: 10),
            ...findingsData.map((f) => pw.Container(
              margin: const pw.EdgeInsets.only(bottom: 10),
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(border: pw.Border.all(color: PdfColors.grey)),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text('Document ID: ${f['documentId']}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                  pw.Text('Type: ${f['type']}'),
                  pw.Text('Status: ${f['status']}'),
                  pw.Text('Description: ${f['description']}'),
                  pw.SizedBox(height: 5),
                  pw.Text('History:'),
                  ...(f['statusHistory'] as List).map((h) => pw.Text('- ${h['status']}: ${h['comment'] ?? ''}')),
                ]
              )
            )),
          ],
        ),
      );

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
      );
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('Error generating report: $e')));
      }
    } finally {
      if(mounted) setState(() => _isGeneratingPdf = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final db = ref.watch(firestoreProvider);

    return StreamBuilder<QuerySnapshot>(
      stream: db.collection('safety_file_submissions')
          .where('contractorId', isEqualTo: widget.contractorId)
          .where('projectId', isEqualTo: widget.projectId)
          .limit(1)
          .snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) return const Center(child: CircularProgressIndicator());

        if (snapshot.data!.docs.isEmpty) {
          return const Center(child: Text('No Safety File Submission for this project yet.'));
        }

        final submissionDoc = snapshot.data!.docs.first;
        final submissionId = submissionDoc.id;
        final submission = SafetyFileSubmission.fromFirestore(submissionDoc);

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Safety File Submission', style: Theme.of(context).textTheme.titleMedium),
                      Text('Status: ${submission.status.name}', style: TextStyle(color: Theme.of(context).colorScheme.primary)),
                    ],
                  ),
                  FilledButton.icon(
                    onPressed: _isGeneratingPdf ? null : () => _generateReport(submissionId),
                    icon: _isGeneratingPdf ? const SizedBox(width: 16, height: 16, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white)) : const Icon(Icons.picture_as_pdf),
                    label: Text(_isGeneratingPdf ? 'Generating...' : 'Download Report'),
                  )
                ],
              ),
            ),
            const Divider(),
            Expanded(
              child: StreamBuilder<QuerySnapshot>(
                stream: db.collection('findings').where('submissionId', isEqualTo: submissionId).snapshots(),
                builder: (ctx, findingSnap) {
                  if (!findingSnap.hasData) return const Center(child: CircularProgressIndicator());
                  final findings = findingSnap.data!.docs.map((d) => Finding.fromFirestore(d)).toList();

                  if (findings.isEmpty) {
                    return const Center(child: Text('No findings logged yet.'));
                  }

                  return ListView.builder(
                    padding: const EdgeInsets.all(16),
                    itemCount: findings.length,
                    itemBuilder: (context, i) {
                      final f = findings[i];
                      return GCard(
                        margin: const EdgeInsets.only(bottom: 12),
                        padding: const EdgeInsets.all(16),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text('Doc: ${f.documentId}', style: const TextStyle(fontWeight: FontWeight.bold)),
                                GStatusTag(
                                  label: f.status.name.toUpperCase(),
                                  color: f.status == FindingStatus.verifiedClosed ? XMTheme.success :
                                         f.status == FindingStatus.cancelled ? Colors.grey : XMTheme.warning,
                                ),
                              ],
                            ),
                            GSpacing.vSm,
                            Text('Type: ${f.type.name}'),
                            Text('Description: ${f.description}'),
                            GSpacing.vMd,
                            if (f.status != FindingStatus.verifiedClosed && f.status != FindingStatus.cancelled)
                              Align(
                                alignment: Alignment.centerRight,
                                child: TextButton.icon(
                                  icon: const Icon(Icons.edit, size: 16),
                                  label: const Text('Update Status'),
                                  onPressed: () => _showUpdateDialog(f),
                                ),
                              )
                          ],
                        ),
                      );
                    },
                  );
                },
              ),
            ),
          ],
        );
      },
    );
  }
}