import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:cloud_functions/cloud_functions.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../models/safety_file_models.dart';
import '../../../core/providers/app_providers.dart';
import '../../../core/utils/ui_utils.dart';
import 'package:sentinel1/core/utils/tenant_firestore_extension.dart';
import 'document_review_dialog.dart';
import 'ai_prescreen_badge.dart';

class SafetyFileSubmissionView extends ConsumerStatefulWidget {
  final String contractorId;
  final String projectId;

  const SafetyFileSubmissionView({
    super.key,
    required this.contractorId,
    required this.projectId,
  });

  @override
  ConsumerState<SafetyFileSubmissionView> createState() =>
      _SafetyFileSubmissionViewState();
}

class _SafetyFileSubmissionViewState
    extends ConsumerState<SafetyFileSubmissionView> {
  final _functions = FirebaseFunctions.instanceFor(region: 'europe-west1');
  bool _isGeneratingPdf = false;

  Future<void> _generateReport(String submissionId) async {
    setState(() => _isGeneratingPdf = true);
    try {
      final res = await _functions
          .httpsCallable('generateSafetyFileReport')
          .call({'submissionId': submissionId});

      final data = res.data as Map;
      final findingsData = data['findings'] as List;

      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          build:
              (context) => [
                pw.Header(level: 0, child: pw.Text('Safety File Audit Report')),
                pw.Text('Submission ID: $submissionId'),
                pw.Text('Generated At: ${data['generatedAt']}'),
                pw.Text('Generated By: ${data['generatedBy']}'),
                pw.SizedBox(height: 20),
                pw.Text(
                  'Findings:',
                  style: pw.TextStyle(
                    fontWeight: pw.FontWeight.bold,
                    fontSize: 18,
                  ),
                ),
                pw.SizedBox(height: 10),
                ...findingsData.map(
                  (f) => pw.Container(
                    margin: const pw.EdgeInsets.only(bottom: 10),
                    padding: const pw.EdgeInsets.all(10),
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColors.grey),
                    ),
                    child: pw.Column(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Text(
                          'Document ID: ${f['documentId']}',
                          style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                        ),
                        pw.Text('Type: ${f['type']}'),
                        pw.Text('Status: ${f['status']}'),
                        pw.Text('Description: ${f['description']}'),
                        pw.SizedBox(height: 5),
                        pw.Text('History:'),
                        ...(f['statusHistory'] as List).map(
                          (h) => pw.Text(
                            '- ${h['status']}: ${h['comment'] ?? ''}',
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
        ),
      );

      await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save(),
      );
    } catch (e) {
      if (mounted) {
        UIUtils.showToast(context, 'Error generating report: $e');
      }
    } finally {
      if (mounted) setState(() => _isGeneratingPdf = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    final db = ref.watch(firestoreProvider);

    return StreamBuilder<QuerySnapshot>(
      stream:
          db
              .tenantCollection(
                ref.watch(currentTenantIdProvider) ?? "",
                'safety_file_submissions',
              )
              .where('contractorId', isEqualTo: widget.contractorId)
              .where('projectId', isEqualTo: widget.projectId)
              .limit(1)
              .snapshots(),
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          return const Center(child: CircularProgressIndicator());
        }

        if (snapshot.data!.docs.isEmpty) {
          return const Center(
            child: Text('No Safety File Submission for this project yet.'),
          );
        }

        final submissionDoc = snapshot.data!.docs.first;
        final submissionId = submissionDoc.id;
        final submission = SafetyFileSubmission.fromFirestore(submissionDoc);

        return Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.all(16),
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Safety File Submission',
                        style: Theme.of(context).textTheme.titleMedium,
                      ),
                      Text(
                        'Status: ${submission.status.name}',
                        style: TextStyle(
                          color: Theme.of(context).colorScheme.primary,
                        ),
                      ),
                    ],
                  ),
                  FilledButton.icon(
                    onPressed:
                        _isGeneratingPdf
                            ? null
                            : () => _generateReport(submissionId),
                    icon:
                        _isGeneratingPdf
                            ? const SizedBox(
                              width: 16,
                              height: 16,
                              child: CircularProgressIndicator(
                                strokeWidth: 2,
                                color: Colors.white,
                              ),
                            )
                            : const Icon(Icons.picture_as_pdf),
                    label: Text(
                      _isGeneratingPdf ? 'Generating...' : 'Download Report',
                    ),
                  ),
                ],
              ),
            ),
            const Divider(),
            Expanded(
              child: StreamBuilder<QuerySnapshot>(
                stream:
                    db
                        .tenantCollection(
                          ref.watch(currentTenantIdProvider) ?? "",
                          'contractor_documents',
                        )
                        .where('submissionId', isEqualTo: submissionId)
                        .snapshots(),
                builder: (ctx, docSnap) {
                  if (!docSnap.hasData) {
                    return const Center(child: CircularProgressIndicator());
                  }
                  final documents =
                      docSnap.data!.docs
                          .map((d) => ContractorDocument.fromFirestore(d))
                          .toList();

                  if (documents.isEmpty) {
                    return const Center(child: Text('No documents uploaded yet.'));
                  }

                  return ListView.builder(
                    padding: const EdgeInsets.all(16),
                    itemCount: documents.length,
                    itemBuilder: (context, i) {
                      final doc = documents[i];
                      return Card(
                        margin: const EdgeInsets.only(bottom: 12),
                        child: ListTile(
                          title: Text(doc.name),
                          subtitle: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Status: ${doc.status}'),
                              if (doc.feedback != null && doc.feedback!.isNotEmpty)
                                Text('Feedback: ${doc.feedback}'),
                              const SizedBox(height: 4),
                              AiPreScreenBadge(documentId: doc.id),
                            ],
                          ),
                          trailing: FilledButton.tonal(
                            onPressed: () => DocumentReviewDialog.show(context, doc),
                            child: const Text('Review'),
                          ),
                        ),
                      );
                    },
                  );
                },
              ),
            ),
          ],
        );
      },
    );
  }
}
